# appId = "ak_KGDmf6TCuShXh"
# appsecret = "vL2rAxuK/VUAt+rjcvgi3g=="
appId="ak_iP3Cia3r7eYlB"
appsecret="0PIfahEa1bpsLXCNsSq4wg=="
domin = "https://openapi.lingxing.com"
domin_bill = "https://openapi.lingxing.com/erp/sc/"